### ISSUE TITLE
Allow ciphertexts to be bigger than 29 bytes

### ISSUE THREAD

**Issue by emduc** [dedis/d-voting#10]
For now ciphertexts are bounded by Kyber to be <= than 29 bytes. It would be better to represent a cipher text by chunks of 29 bytes. To make sure comparisons between encrypted and decrypted ballots is impossible, the size of all ballots should still be the same

**Comment by nkcr** [comment]
To support that the Kyber library must support shuffling of sequences, instead of only single pairs. This is being added in Kyber and should soon be part of the library:
https://github.com/dedis/kyber/pull/457
