### ISSUE TITLE
Frontend correct redirection after Action

### ISSUE THREAD

**Issue by badrlarhdir** [dedis/d-voting#117]
Fixes to have correct redirection
- When creating an election the user should be redirected to the election show page of this new election
- When casting a vote the user should be redirected to the correct page ( show page or elections table depending on where he came from )
- The back button of show results should redirect the user to the correct page  ( show page or elections table depending on where he came from )

**Comment by nkcr** [comment]
Bonus:

- when I access a protected page (like create an election) and I'm not logged in, I am redirected to the login page. When I log from that page, I should then be redirected to the page I tried to access (create an election in this case).
