### ISSUE TITLE
Web backend: database for the proxies' addresses

### ISSUE THREAD

**Issue by cmsigrist** [dedis/d-voting#125]
The web backend needs to have a database containing the mapping between the IP address of a node and the IP address of its proxy.
When the frontend makes a GET request on `/api/elections/ElectionID/proxies`, the web backend must return the mapping for each node participating in the given election.
It should also be possible to update this mapping by making a POST request (on the same endpoint ?)  and giving the new node and proxy addresses.

**Comment by nkcr** [comment]
The endpoints should be as follow (all URLs are prefixed with `/api/elections/:ElectionID/`:

**1. Create a mapping:**

POST /proxies

input:
```
{"Proxies": [
  {"123.456.78.9:9000": "https://example.com/"},
  {"111.222.333.444:9000": "https://blabla.ch/"}
]}
```

**2. Update a mapping:**

PUT /proxies

input:
```
{"Proxies": [
  {"123.456.78.9:9000": "https://example.com/"},
  {"111.222.333.444:9000": "https://blabla.ch/"}
]}
```

**3. Delete a mapping:**
DELETE /proxies

**4. Get a mapping:**

GET /proxies

output:
```
{"Proxies": [
  {"123.456.78.9:9000": "https://example.com/"},
  {"111.222.333.444:9000": "https://blabla.ch/"}
]}
```
