### ISSUE TITLE
Adds an authorization  mechanism 

### ISSUE THREAD

**Issue by emduc** [dedis/d-voting#150]
Hi,

As a matter of scalability, I was thinking it made sense to offer the possibility to give a list of scipers who are allowed to vote in a given election. Since the nodes rely on the web backend's signature, it is possible to include it as a requirement for the web backend to sign the tx (is it desirable?).
Similarly, it could be a good idea that the list of admins who can act on the election is given when the election is created (rather than having all admins being able to act on all elections).

**Comment by nkcr** [comment]
Yes, this is indeed a desirable feature that the web-backend should handle.

**Comment by PascalinDe** [comment]
#305 is a duplicate, but a more detailed one, so I'll close this one and we'll continue over there
