### ISSUE TITLE
THREAT - A user who is not an admin or operator cannot vote.

### ISSUE THREAD

**Issue by Flamewind97** [dedis/d-voting#253]
## Scenario
Every action from a user who is not an admin or operator will become unauthorized, including casting a vote. An authenticated user should able to cast a vote even if they are not an operator or admin 

## Source
web/backend/src/Server.ts
```js
// Secure /api/evoting to admins and operators
app.use('/api/evoting/*', (req, res, next) => {
  if (!isAuthorized(req.session.userid, SUBJECT_ELECTION, ACTION_CREATE)) {
    res.status(400).send('Unauthorized - only admins and operators allowed');
    return;
  }
  next();
});
```

## Breaking Property
Availability, Authorization

## Risk
CVSS Score: [5.7/10](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:N/A:H)

## Mitigation
Backend should let an authenticated user have the ability to vote.

**Comment by Ghita2002** [comment]
It's now fixed !
