### ISSUE TITLE
[Authorization] Missing permission for voting

### ISSUE THREAD

**Issue by lanterno** [dedis/d-voting#305]
The current version of the "web backend" service allows any user to vote as long as they are logged-in through EPFL's SSO "tequila". 

This doesn't match the requirements, as **each election will require a different set of users who are allowed to vote depending on the election.**

A new permission "Can vote" is needed on the object level. 
So a user A should have a "can vote" permission on form/election "X".

This will also modifications to the current Authorization framework as it's not currently configured to allow object-level permissions.

ToDo:
- [x] Add a "can vote" permission on an object level.  
- [x] Add ability to assign a user a "can vote" permission on a specific election/form from the CLI
- [x] Validate that logged-in user has "can vote" permission on an election/form before allowing the user to vote on an election/form.

Extra:
- [ ] Use the 3 roles **Admin**, **Operator**, **Voter** in the backend using **Casbin library**

Note: 
We use the [Casbin library](https://casbin.org/docs/overview/) to implement **Authorization**

**Comment by lanterno** [comment]
Last item is still not done yet!

**Comment by lanterno** [comment]
From your experience already, do you think this is completed now, or should we do something else?

**Comment by PascalinDe** [comment]
> @ineiti @PascalinDe Do you think this is completed now, or should we do something else?

I'll close this, further improvements will be in new tickets
