### ISSUE TITLE
Internalisation - forms are not correctly displayed in list of forms

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#309]
![Screenshot 2023-08-25 at 15-09-21 D-Voting](https://github.com/dedis/d-voting/assets/15922677/cdcbf0f5-9ac2-486c-a100-9714abe02c60)

no title or clickable link is shown, making the form inaccessible

the problem seems to be in the frontend, since the backend returns the correct data:

`{"Forms":[{"FormID":"78715f535155153ff37846149391ad128b8f5f423d9a9c9e476fa9f98e9dfbfb","Title":"{\"en\":\"Starter Pokémon\",\"fr\":\"\",\"de\":\"\"}","Status":0,"Pubkey":""},{"FormID":"49f21d11e17b593c1b45146d9fb249f25d2a1bd4642ec98c2892a3fadf4b3f29","Title":"{\"en\":\"Starter Pokémon\",\"fr\":\"\",\"de\":\"\"}","Status":0,"Pubkey":""}]}`

**Comment by PascalinDe** [comment]
reproduced on Firefox 116 and Chromium 115

**Comment by PascalinDe** [comment]
the problem is a mismatch between the interface and the data returned from the backend, I'm currently working on a fix

**Comment by PascalinDe** [comment]
@pierluca the problem is the way that the language send by the browser is handled - only "en", "fr", "de" are currently taken into account, but mine sends "en-US", so an empty field gets returned

I'd let i18n handle the language as one can define fallbacks there in case the language is unknown

my question is: should one of the title languages be required (i.e. always an English title) as opposed to "as long as it has *any* title it's fine"? imho, one language site should always have every content (French? English? what's the policy at EPFL?)

**Comment by PascalinDe** [comment]
I think the whole internalization needs to be overhauled

but that would probably take some time - I've added a WIP here that shows the "get it to work while also trying to steer it into a better direction variant" https://github.com/dedis/d-voting/pull/313 so that might be a good starting point

**Comment by PascalinDe** [comment]
https://github.com/dedis/d-voting/pull/313

**Comment by PascalinDe** [comment]
the wrong PR got linked, it should've been https://github.com/dedis/d-voting/pull/313

**Comment by pierluca** [comment]
I agree that the whole i18n needs to be overhauled. That's probably one of the most critically broken things in the front-end and the APIs.

> I meant "there should be at least one language version that has 100% content in that language and missing content in the other languages should default to that language's version"

this seems the correct approach, not the 

> as long as it has any title it's fine

I wouldn't force it to be English or French though, but that's probably something that Lindo & Giovanni can clarify.
