### ISSUE TITLE
UI - proxy management is not working correctly

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#310]
* trying to add a new proxy seemingly always raises an error, but the proxy entry is created anyway and reloading the page shows it
* editing an existing proxy seemingly always raises an error on confirmation/cancel and the entry is subsequently *deleted* and no longer in the list when reloading the page
* deleting a proxy from the list makes the frontend freeze

**Comment by ineiti** [comment]
Fixed in #c4dt/d-voting#24
