### ISSUE TITLE
Internalisation: grouping ticket

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#320]
This ticket is to group smaller tickets related to internalisation:

* [x] create necessary tickets (see discussion below)
* [x] #328 
* [ ] #329

**Comment by ineiti** [comment]
Even better, use a `Map`. So you don't need to have `Objects.entries(titles)` if you want to use an iterator.

**Comment by PascalinDe** [comment]
grouping tickets are not working well for this project, I'll close this one
