### ISSUE TITLE
Election finalisation condition

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#326]
election can be closed/shuffled/... although only ballots from a single user have been cast

**Comment by ineiti** [comment]
Not sure whether this is only because we have the debug-feature of random SCIPERS enabled. Did you test it with _really_ only one vote, and not multiple votes with random SCIPERS from the same person?

**Comment by PascalinDe** [comment]
yes, that's what I meant

to avoid misunderstandings: it is not an "enabled debug-feature", it is a hard-coded circumvention of the proper behaviour as pointed out in #248 

but since this ticket is a duplicate of that one, I'll close it
