### ISSUE TITLE
Internalisation: initial language is not set properly

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#328]
initial language is not set to one of the three languages provided (en, fr, de), which causes some pages to not display properly (as no translation may exist for the initial language)

**Comment by ineiti** [comment]
@PascalinDe but if you look at https://github.com/c4dt/d-voting/blob/main/web/frontend/src/language/Configuration.ts#L17 it seems to be set correctly, no?

Can you give some example where it doesn't work?

**Comment by ineiti** [comment]
@PascalinDe I have a PR in c4dt/d-voting#39, but I'm not sure it's actually doing something useful :)
