### ISSUE TITLE
Vote - Rank: Incorrect results are displayed

### ISSUE THREAD

**Issue by PascalinDe** [dedis/d-voting#331]
The results for ranking are thus:

![Screenshot 2023-09-01 at 10-53-35 D-Voting](https://github.com/dedis/d-voting/assets/15922677/c7d01b3f-86fb-4e2e-ad5f-24483b15dde3)

With the following votes having been cast:

* "Red" was once 1, once 2 and once 3
* "Green" was twice 1, and once 2
* "Blue" was once 2 and twice 3

The results don't seem to correspond to the explainer:

> Results of rank question corresponds to the percentage of the score a candidate has. Each voter gives candidates points by ranking them from 1 to N (lower is better). The score corresponds to the sum of the points a candidate got and is divided by the total number of points attributed across all ballots, and subtracted to one.

(I interpreted "substracted to one" as "substracted from one", as this corresponds to "the points that this candidate did not receive" and would thus lead to it being ranked higher in a "lower is better" ranking)

* 18 points have been awarded in total
* "Red" has 6 points => 6/18  => 1 - 6/18 ~= 0.66 => ~ 66% OK
* "Green" has 4 points => 4/18 => 1 - 4/18 ~= 0.77 => ~ 77% =/= 88.89% 
* "Blue" has 8 points => 8/18 => 1 - 8/18 ~= 0.55 => ~ 55% =/= 44.44%

The exported JSON contains the correct number of "points" for each candidate:

```
{
  "MainTitle": "Colours",
  "TitleFr": "",
  "TitleDe": "",
  "NumberOfVotes": 3,
  "Ballots": [
    {
      "BallotNumber": 1,
      "Results": [
        {
          "Title": "Colours"
        },
        {
          "Title": "{\"en\":\"RGB\",\"fr\":\"\",\"de\":\"\"}",
          "Results": [
            {
              "Rank": "1",
              "Choice": "{\"en\":\"Red\"}"
            },
            {
              "Rank": "2",
              "Choice": "{\"en\":\"Green\"}"
            },
            {
              "Rank": "3",
              "Choice": "{\"en\":\"Blue\"}"
            }
          ]
        }
      ]
    },
    {
      "BallotNumber": 2,
      "Results": [
        {
          "Title": "Colours"
        },
        {
          "Title": "{\"en\":\"RGB\",\"fr\":\"\",\"de\":\"\"}",
          "Results": [
            {
              "Rank": "1",
              "Choice": "{\"en\":\"Green\"}"
            },
            {
              "Rank": "2",
              "Choice": "{\"en\":\"Red\"}"
            },
            {
              "Rank": "3",
              "Choice": "{\"en\":\"Blue\"}"
            }
          ]
        }
      ]
    },
    {
      "BallotNumber": 3,
      "Results": [
        {
          "Title": "Colours"
        },
        {
          "Title": "{\"en\":\"RGB\",\"fr\":\"\",\"de\":\"\"}",
          "Results": [
            {
              "Rank": "1",
              "Choice": "{\"en\":\"Green\"}"
            },
            {
              "Rank": "2",
              "Choice": "{\"en\":\"Blue\"}"
            },
            {
              "Rank": "3",
              "Choice": "{\"en\":\"Red\"}"
            }
          ]
        }
      ]
    }
  ]

```

**Comment by pierluca** [comment]
This can either be seen as a documentation or an implementation problem.
As I understand it, they're implementing a variation of [Borda count](https://en.wikipedia.org/wiki/Borda_count), although typically Borda count would typically rank higher-is-better (from 0 to N-1).
The numbers in your demonstration add up if instead of giving "1, 2, 3, ...", voters give "0, 1, 2, ..." points.
Basically, we're dealing with an off-by-one, it's probably not worth disabling for such a small issue.

**Comment by PascalinDe** [comment]
OK, in that case, we need to fix the docstring in the interface
