### ISSUE TITLE
THREAT - Check if userId can be modified

### ISSUE THREAD

**Issue by ineiti** [dedis/d-voting#356]
I'm not sure how the backend handles the `session.userId` of a request here:

https://github.com/dedis/d-voting/blob/main/web/backend/src/Server.ts#L249

Is it possible for an attacker to create a cookie with a different userId? Or is there some signature that is making sure the userId is correctly given by the user?

**Comment by pierluca** [comment]
After looking into this, it's pretty obvious this is not a threat.

ExpressJS session management has a "secret" parameter to secure the sessions.
https://www.npmjs.com/package/express-session

And it gets configured here:
https://github.com/dedis/d-voting/blob/main/web/backend/src/Server.ts#L99

**Comment by ineiti** [comment]
Thanks for looking into this. Usage of `MemoryStore` seems to be problematic as it leaks memory. I opened #358
